from __future__ import annotations

from types import SimpleNamespace

import pytest

from stanag4609.audio.pyav import PyAVAudioDecoder
from stanag4609.st1001 import AudioCodec, AudioFrameParser


class _Packet:
    def __init__(self, data: bytes) -> None:
        self.data = data


class _Context:
    def __init__(self) -> None:
        self.thread_count = 0
        self.calls: list[_Packet | None] = []

    def decode(self, packet: _Packet | None) -> list[object]:
        self.calls.append(packet)
        return [] if packet is None else [SimpleNamespace(packet=packet)]


class _CodecContext:
    created: tuple[str, str] | None = None
    context = _Context()

    @classmethod
    def create(cls, name: str, mode: str) -> _Context:
        cls.created = (name, mode)
        cls.context = _Context()
        return cls.context


FAKE_AV = SimpleNamespace(CodecContext=_CodecContext, Packet=_Packet)


def _layer_frame(codec: AudioCodec = AudioCodec.MPEG1_LAYER_II):
    raw = (
        bytes.fromhex("FFFC8444") + bytes(380)
        if codec is AudioCodec.MPEG1_LAYER_II
        else bytes.fromhex("FFF584C0") + bytes(380)
    )
    return AudioFrameParser(codec).feed(raw)[0]


def _aac_frames():
    # Two MPEG-2 AAC-LC silent ADTS frames generated by FFmpeg 7.1.1.
    raw = bytes.fromhex(
        "fff94c8003dffcde02004c61766336312e31392e31303100422008c11838"
        "fff94c8001bffc211004608c1c"
    )
    return AudioFrameParser(AudioCodec.MPEG2_AAC_LC).feed(raw)


def test_pyav_decoder_adapts_codec_context_and_native_frames() -> None:
    decoder = PyAVAudioDecoder(
        AudioCodec.MPEG1_LAYER_II,
        av_module=FAKE_AV,
        thread_count=2,
    )
    assert _CodecContext.created == ("mp2", "r")
    assert decoder.codec_context.thread_count == 2

    source = _layer_frame()
    decoded = decoder.decode(source)
    assert len(decoded) == 1
    assert decoded[0].packet.data == source.raw
    assert decoder.submitted_frames == 1
    assert decoder.decoded_frames == 1

    assert decoder.flush() == ()
    assert decoder.flush() == ()
    assert decoder.finished
    with pytest.raises(RuntimeError, match="flushed"):
        decoder.decode(source)


def test_pyav_decoder_supports_mpeg2_layer_ii_and_aac_codec_names() -> None:
    PyAVAudioDecoder(AudioCodec.MPEG2_LAYER_II, av_module=FAKE_AV)
    assert _CodecContext.created == ("mp2", "r")
    PyAVAudioDecoder(AudioCodec.MPEG2_AAC_LC, av_module=FAKE_AV)
    assert _CodecContext.created == ("aac", "r")


def test_pyav_decoder_rejects_wrong_frames_and_invalid_configuration() -> None:
    decoder = PyAVAudioDecoder(AudioCodec.MPEG1_LAYER_II, av_module=FAKE_AV)
    with pytest.raises(TypeError, match="CompressedAudioFrame"):
        decoder.decode(object())  # type: ignore[arg-type]
    with pytest.raises(ValueError, match="codec"):
        decoder.decode(_layer_frame(AudioCodec.MPEG2_LAYER_II))

    with pytest.raises(TypeError, match="AudioCodec"):
        PyAVAudioDecoder("mp2", av_module=FAKE_AV)  # type: ignore[arg-type]
    with pytest.raises(ValueError, match="thread_count"):
        PyAVAudioDecoder(AudioCodec.MPEG1_LAYER_II, av_module=FAKE_AV, thread_count=0)
    with pytest.raises(TypeError, match=r"CodecContext\.create"):
        PyAVAudioDecoder(AudioCodec.MPEG1_LAYER_II, av_module=object())


def test_pyav_decoder_decodes_many_and_validates_backend_result() -> None:
    decoder = PyAVAudioDecoder(AudioCodec.MPEG1_LAYER_II, av_module=FAKE_AV)
    source = _layer_frame()
    assert len(decoder.decode_many((source, source))) == 2
    assert decoder.submitted_frames == 2

    decoder.codec_context.decode = lambda _packet: 1  # type: ignore[method-assign]
    with pytest.raises(TypeError, match="iterable"):
        decoder.decode(source)


def test_pyav_optional_dependency_error_is_actionable(monkeypatch: pytest.MonkeyPatch) -> None:
    def missing(_name: str) -> object:
        raise ModuleNotFoundError

    monkeypatch.setattr("stanag4609.audio.pyav.importlib.import_module", missing)
    with pytest.raises(RuntimeError, match=r"audio-pyav"):
        PyAVAudioDecoder(AudioCodec.MPEG1_LAYER_II)


@pytest.mark.integration
def test_real_pyav_decodes_all_st1001_codecs_when_installed() -> None:
    pytest.importorskip("av")
    cases = (
        (AudioCodec.MPEG1_LAYER_II, (_layer_frame(),), 1_152, 48_000, "stereo"),
        (
            AudioCodec.MPEG2_LAYER_II,
            (_layer_frame(AudioCodec.MPEG2_LAYER_II),),
            1_152,
            24_000,
            "mono",
        ),
        (AudioCodec.MPEG2_AAC_LC, _aac_frames(), 1_024, 48_000, "stereo"),
    )
    for codec, source, samples, rate, layout in cases:
        decoder = PyAVAudioDecoder(codec)
        frames = decoder.decode_many(source)
        assert len(frames) == len(source)
        assert all(frame.samples == samples for frame in frames)
        assert all(frame.sample_rate == rate for frame in frames)
        assert all(frame.layout.name == layout for frame in frames)
        assert decoder.flush() == ()
